Lots of improvements for kaisen-build (automation, build process...)

diff --git a/kaisen-build/kaisen-build b/kaisen-build/kaisen-build
--- a/kaisen-build/kaisen-build
+++ b/kaisen-build/kaisen-build
@@ -7,107 +7,107 @@ GREEN='\e[1;32m'
 YELLOW='\e[0;33m'
 RED='\e[1;31m'
 
-export variant=$2
-export version=$3
+help() {
+	echo -e "\e[1;32mKaisen Linux ISO build system
 
-if [[ "$EUID" -ne 0 ]]; then
-	echo -e $RED "Run this script as root or with the sudo command."
-	exit 1
-fi
+\e[0;33mUSAGE
+	\e[1;35mbuild\e[0;33m: \e[1;36msudo ./kaisen-build \e[1;35m-v\e[0;33m \e[1;36mVARIANT \e[1;35m-r\e[0;33m \e[1;36mRELEASENUMBER
+	\e[1;35mclean\e[0;33m: \e[1;36msudo ./kaisen-build \e[1;35m-c
+	\e[1;35mhelp\e[0;33m: \e[1;36msudo ./kaisen-build \e[1;35m-h
 
-log() {
-	mkdir -p /var/log/kaisen-build
-	exec > >(tee /var/log/kaisen-build/kaisen-build-$variant-$DATE.log) 2>&1
-}
-
-function explaination() {
-	echo -e $GREEN "Kaisen Linux ISO build system
-
-USAGE
-	cd ~/kaisen-build (with no root user)
-	sudo ./kaisen-build <action> <variant> <version>
-
-EXPLAINATION
-	action - help, build, clean
-		help: display help
-		build: build iso
-		clean: delete generated files created by kaisen-build
-
-	variant - MATE, XFCE, KDE, LXQT, SR, NETINST, CUSTOM
-		the graphical interface to use (MATE, XFCE, KDE or LXQT)
-		or use System Rescue version (Only technicians tools, with or not GUI, SR variant)
-		or use network installer (no live, NETINST variant)
-
-	version - select your version number
+\e[0;33mEXPLAINATION
+		Arguments can be used with this script:
+		\e[1;35m-h\e[0;33m|\e[1;35m--help\e[0;33m: display help
+		\e[1;35m-c\e[0;33m|\e[1;35m--clean\e[0;33m: Completely remove files and confs generated by kaisen-build
+		\e[1;35m-r\e[0;33m|\e[1;35m--release\e[0;33m: Select your release number, example \e[1;36m2.0
+		\e[1;35m-v\e[0;33m|\e[1;35m--variant\e[0;33m: \e[1;36mMATE\e[0;33m, \e[1;36mXFCE\e[0;33m, \e[1;36mKDE\e[0;33m, \e[1;36mLXQT\e[0;33m, \e[1;36mSR\e[0;33m, \e[1;36mNETINST\e[0;33m, \e[1;36mCUSTOM\e[0;33m
+			   The graphical interface to use (\e[1;36mMATE\e[0;33m, \e[1;36mXFCE\e[0;33m, \e[1;36mKDE\e[0;33m or \e[1;36mLXQT\e[0;33m)
+			   Or use System Rescue release (Only technicians tools, with or not GUI, \e[1;36mSR\e[0;33m variant)
+			   Or use NETwork INSTaller (no live, \e[1;36mNETINST\e[0;33m variant)
+			   Or use your own configurations (\e[1;36mCUSTOM\e[0;33m variant)
 
 EXAMPLE
-	sudo ./kaisen-build build CUSTOM 1.0
-	or sudo ./kaisen-build build CUSTOM
+	To build an ISO with the short options:
+	\e[1;36msudo ./kaisen-build \e[1;35m-v \e[1;36mMATE \e[1;35m-r \e[1;36m2.1\e[0;33m
+	To build an ISO with the long options:
+	\e[1;36msudo ./kaisen-build \e[1;35m--variant \e[1;36mMATE \e[1;35m--release \e[1;36m2.1\e[0;33m
+	To build an ISO with the long options with your own configurations:
+	\e[1;36msudo ./kaisen-build \e[1;35m--variant \e[1;36mCUSTOM \e[1;35m--release \e[1;36m0.1\e[0;33m
 
 DOCUMENTATION
-	https://kaisenlinux.org/documentation/faq.html#how-to-build-custom-iso
+	\e[1;32mhttps://kaisenlinux.org/documentation/faq.html#how-to-build-custom-iso\e[0;33m
 "
+exit 0
 }
 
-function kaisen-build() {
-if [ -z $variant ]; then
-	echo -e $RED "Launch this script with a valid variant name."
-	exit 1
-fi
+clean() {
+[ -x auto/clean ] && ./auto/clean;tput init && exit 0
+}
 
-if [ ! -e variant/$variant ] && [ ! -d variant/$variant ]; then
-	echo -e $RED "The variant $variant does not exist or does not a folder in variant folder."
-	exit 1
-fi
-
-if [ -z $version ]; then
-	echo -e $RED "Launch this script with a version number."
-	exit 1
-fi
-
-while [[ $OPTION != "y" && $OPTION != "n" ]]; do
-    read -rp "$(echo -e $GREEN "Would you like create a log file? [y/n]")" OPTION
-	echo ""
+ARGS=$(getopt -o r:v:hc -l release:,variant:,help,clean -- "$@")
+eval set -- "$ARGS"
+while true
+do
+        case "$1" in
+                -h|--help) help; ;;
+                -c|--clean) clean; ;;
+                -r|--release) RELEASE=$2; shift 2; ;;
+                -v|--variant) VARIANT=$2; shift 2; ;;
+                --) shift; break; ;;
+                 *) echo -e $RED "Internal error, unhandled option: $1"; exit 1; ;;
+        esac
 done
 
-if [[ $OPTION = "y" ]]; then
-	log
-	echo -e $GREEN "Log file created in /var/log/kaisen-build/kaisen-build-$variant-$DATE.log";tput init
-	echo ""
-else
-	echo -e $YELLOW "No log file created.";tput init
-	echo ""
+if [[ "$EUID" -ne 0 ]]; then
+        echo -e $RED "Run this script as root or with the sudo command."
+        exit 1
 fi
 
-case $variant in
+if [ ! -e variant/$VARIANT ] && [ ! -d variant/$VARIANT ]; then
+        echo -e $RED "The variant $VARIANT does not exist or does not a folder in the variant folder."
+        exit 1
+fi
+
+if [ -z $VARIANT ]; then
+	VARIANT="MATE"
+fi
+
+if [ -z $RELEASE ]; then
+        RELEASE="NULL"
+fi
+
+export VARIANT
+export RELEASE
+
+[ -x auto/clean ] && ./auto/clean;tput init
+
+sed -i "s/Kaisen Linux Rolling Live/Kaisen Linux Rolling $VARIANT $RELEASE Live/g" common/includes.binary/boot/grub/grub.cfg
+sed -i "s/Kaisen Linux Rolling Install/Kaisen Linux Rolling $VARIANT $RELEASE Install/g" common/includes.binary/boot/grub/grub.cfg
+sed -i "s/Kaisen Linux/Kaisen Linux $VARIANT $RELEASE/g" common/includes.binary/.disk/info
+sed -i "0,/Kaisen Linux Rolling/ s/Kaisen Linux Rolling/Kaisen Linux Rolling $VARIANT $RELEASE/" common/includes.binary/isolinux/menu.cfg
+sed -i "s/Kaisen Linux NETINST/Kaisen Linux NETINST "$RELEASE"/g" variant/NETINST/simple-cdd.conf
+sed -i "s/Kaisen Linux Rolling NETINST/Kaisen Linux Rolling NETINST $RELEASE/g" variant/NETINST/simple-cdd.conf variant/NETINST/hook
+
+case $VARIANT in
 	KDE|LXQT|MATE|XFCE|SR)
-		lb clean
-		rm -rf cache config unpacked-initrd .build tmp images || true
 		lb build
-		mv live-image-amd64.hybrid.iso ../kaisenlinuxrolling$version-amd64-$variant.iso
-		echo -e $YELLOW "ISO can be found in ../kaisenlinuxrolling$version-amd64-$variant.iso";tput init
-		lb clean
-		rm -rf cache config unpacked-initrd .build || true
-		echo -e $GREEN "All files generated by kaisen-build has been deleted successfully."
+		mv live-image-amd64.hybrid.iso ../kaisenlinuxrolling$RELEASE-amd64-$VARIANT.iso
+		echo -e $YELLOW "ISO can be found in ../kaisenlinuxrolling$RELEASE-amd64-$VARIANT.iso";tput init
+		[ -x auto/clean ] && ./auto/clean;tput init
 	;;
 esac
 
-case $variant in
+case $VARIANT in
     CUSTOM)
-		lb clean
-		rm -rf cache config unpacked-initrd .build tmp images || true
 		lb build
-		mv live-image-amd64.hybrid.iso ../kaisenlinuxCUSTOM-amd64-$version.iso
-		echo -e $YELLOW "ISO can be found in ../kaisenlinuxCUSTOM-amd64-$version.iso";tput init
-		lb clean
-		rm -rf cache config unpacked-initrd .build || true
-		echo -e $GREEN "All files generated by kaisen-build has been deleted successfully."
+		mv live-image-amd64.hybrid.iso ../kaisenlinuxCUSTOM-amd64-$RELEASE.iso
+		echo -e $YELLOW "ISO can be found in ../kaisenlinuxCUSTOM-amd64-$RELEASE.iso";tput init
+		[ -x auto/clean ] && ./auto/clean;tput init
 	;;
 esac
 
-case $variant in
+case $VARIANT in
 	NETINST)
-		rm -rf cache config unpacked-initrd .build tmp images || true
 		build-simple-cdd \
 		--profiles kaisen \
 		--auto-profiles kaisen \
@@ -117,31 +117,8 @@ case $variant in
 		--conf variant/NETINST/simple-cdd.conf \
 		--dist kaisen-rolling \
 		--debian-mirror https://deb.kaisenlinux.org
-		mv images/kaisen-Rolling-amd64-NETINST-1.iso ../kaisenlinuxrolling$version-amd64-$variant.iso
-		echo -e $YELLOW "ISO can be found in ../kaisenlinuxrolling$version-amd64-$variant.iso"
-		rm -rf tmp images || true
-		echo -e $GREEN "All files generated by kaisen-build has been deleted successfully."
-	;;
-esac
-}
-
-function clean() {
-	lb clean
-	rm -rf cache config unpacked-initrd .build tmp images || true
-	echo -e $GREEN "All files generated by kaisen-build has been deleted successfully."
-}
-
-case $1 in
-		build)
-			kaisen-build
-	;;
-		clean)
-			clean
-	;;
-		help)
-			explaination
-	;;
-		*)
-			explaination
+		mv images/kaisen-Rolling-amd64-NETINST-1.iso ../kaisenlinuxrolling$RELEASE-amd64-$VARIANT.iso
+		echo -e $YELLOW "ISO can be found in ../kaisenlinuxrolling$RELEASE-amd64-$VARIANT.iso"
+		[ -x auto/clean ] && ./auto/clean;tput init
 	;;
 esac
